[phases.setup]
nixpkgs = ["python39", "python39Packages.pip", "gcc"]

[phases.build]
command = "cd backend && python3 -m pip install -r requirements.txt"

[phases.start]
command = "cd backend && gunicorn --bind 0.0.0.0:$PORT BackEnd.wsgi:application"
