# Generated by Django 5.0.6 on 2025-03-05 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('lugar_id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('viaje_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('asientos_disponibles', models.IntegerField()),
                ('costo_por_asiento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes_destino', to='viajes.lugar')),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes_origen', to='viajes.lugar')),
            ],
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('postulacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=10)),
                ('fecha_hora_postulacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.viaje')),
            ],
        ),
    ]
