# Generated by Django 5.0.6 on 2024-06-21 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0003_alter_viaje_destino_direccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulacion',
            name='id',
        ),
        migrations.AddField(
            model_name='postulacion',
            name='postulacion_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
